export type {
  MarketPhase,
  ActionBias,
  DetectedRiskType,
  MultiTimeframeAlignment,
  MultiTimeframeResultSummary,
  MultiTimeframeScanSummary,
  PrimaryStructure,
  ScannerObservation,
  ScannerObservationKey,
  ScannerObservationScope,
  ScannerObservationSeverity,
  ScannerExplanation,
  ScannerExplanationKey,
  ScannerReviewKey,
  ScannerReviewText,
  ScannerSignal,
  ScannerSignalLabel,
  ScannerSignalState,
  ScanResult,
} from "@/lib/shared/scannerTypes";
